### ISSUE TITLE
[BUG] Danger doesn't add a comment if the commented line is not part of the diff

### ISSUE THREAD

**Issue by f-meloni** [danger/danger-js#1207] opened 2022-02-08 14:55 UTC
**Describe the bug**
If your Dangerfile generates an inline comment, which points to a line which not part of your current PR's diff, Danger doesn't post anything on the PR.
The inline comment API doesn't work if the item is not part of the diff, however Danger used to gather all the failed inline comments, and post them as part of the main Danger comment.

**To Reproduce**
1. Create a Dangerfile which comments at line 2 of a random file
2. Change a different file
3. Open a PR

**Expected behavior**
Danger posts a comment with the failure

**Your Environment**

 | software         | version
| ---------------- | -------
| danger.js          | 11.0.2
| danger-swift |  3.12.1
| Operating System | MacOS

**Additional context**
I've investigated it a little bit and saw that a new inline logic is been introduced https://github.com/danger/danger-js/pull/1176 and that might be related

**Comment by fbartho** [comment] 2022-03-14 21:54
What CI are you testing against?

This definitely used to work on Github, but my team hasn't generated this kind of issue in a while.

**Comment by orta** [comment] 2022-03-21 16:35
`danger local` posts to the CLI by default, `danger ci` would post to your pull request and not the CLI

**Comment by carocad** [comment] 2022-03-21 20:09
@orta yes, I know. I was providing the output to show that the output is there but it is not been shown in the PR. Hope it helps.

**Comment by ThomasGHenry** [comment] 2022-04-01 00:20
Similar thing for us. fail() prints to the github action output, but the status remains successful and there's no comment on the PR. This used to work. I'm not sure when it stopped.

**Comment by f-meloni** [comment] 2022-04-08 13:27
It might be (just a guess) that before we were trying to post the comments one by one, so if one was failing, that was added to the Danger "global" comment, while now it tries to make only one single review with all the comments, so if it fails to write some of the comments, the API request doesn't fail so the failing comments are not added to the global comment anymore.

**Comment by fbartho** [comment] 2022-04-08 17:15
@f-meloni I think your guess feels really probable.

Is there any way to resolve this? or is this a gap in the Github API? 

In our repo we had some tools that were regularly adding comments to non-edited files (when a configuration change was needed due to changes elsewhere), so I was able to add a quick user-side workaround for that case, but that still leaves a gap for cases like when you add a new eslint warning that triggers elsewhere in a file that you did actually edit (those comments would still be missing).
There's a way for us to fix this by checking if every line you try to comment on is present in one of the git-dsl's diff chunks, but I worry that that would materially slow down the community. -- I'm not sure we're prefetching all the diff chunks for every source file. -- If the git-diff-chunk fetching is aggressively cached, maybe this won't be a problem, as you'd only pay the price once per file you need to comment on, which I think is fair. 

What do you think @orta? Would aggressively caching git-diff-chunk fetching + pre-filtering all "inline" comments to see if they're a valid comment target be acceptable?

**Comment by orta** [comment] 2022-04-08 21:37
> What do you think @orta? Would aggressively caching git-diff-chunk fetching + pre-filtering all "inline" comments to see if they're a valid comment target be acceptable?

I think we're already doing this

**Comment by fbartho** [comment] 2022-04-08 22:08
If we’re fetching all diff chunks is aggressively cached, then the code that decides to post a review could test every file/line combo for candidate inline comments & move them into the main report if the comment is likely to fail.

I think that’s reasonable for the DangerJS GitHub provider to implement. Any concerns? (Performance?)

**Comment by orta** [comment] 2022-04-14 12:47
An alternative method is to look for failing requests for each inline comment and then paste those into the main thread, which I think is how it is implemented in danger ruby

**Comment by Rouby** [comment] 2022-04-21 08:19
I just took a look at the code I wrote and I think the bug is that failing inline reviews don't get added to the "leftover" inline result array. I have created a PR that _should_ address this.

**Comment by carocad** [comment] 2022-04-28 08:29
I can confirm that version [11.0.4](https://github.com/danger/danger-js/releases/tag/11.0.4) fixes the issue on our end.

**Comment by airtonix** [comment] 2022-08-30 22:56
It's super unfortunate that a patch release changed the version of nodejs it means we're excluded from this fix. Looking through the PR i can't see anything that would require a nodejs version change.

**Comment by fbartho** [comment] 2023-05-19 19:24
Closing this ticket since it appears resolved as of April 28, 2022 https://github.com/danger/danger-js/issues/1207#issuecomment-1111897695

**Closed by fbartho** 2023-05-19 19:24 UTC
Labels: bug, [platform] GitHub
