### ISSUE TITLE
BitBucket Server doesn't allow removal of comments with replies

### ISSUE THREAD

**Issue by azz** [danger/danger-js#670] opened 2018-09-25 04:28 UTC
Danger crashes when trying to delete its own comment if that comment has replies 😢 .

```
$ /work/7c55ecc4ac081e40/node_modules/.bin/danger ci
No issues or messages were sent. Removing any existing messages.
Request failed [409]: https://bitbucket.server/rest/api/1.0/projects/PROJ/repos/repo/pull-requests/229/comments/43708?version=1
Response: {
  "errors": [
    {
      "context": null,
      "message": "This comment has replies which must be deleted first.",
      "exceptionName": "com.atlassian.bitbucket.comment.CommentDeletionException"
    }
  ]
}
Error:  Error: Failed to delete comment "43708
    at BitBucketServerAPI.<anonymous> (/work/7c55ecc4ac081e40/node_modules/danger/distribution/platforms/bitbucket_server/BitBucketServerAPI.js:324:39)
```

Simple fix: Edit the comment instead of deleting it, if it has replies.

Danger version: `3.6.5`.

**Comment by langovoi** [comment] 2018-11-26 19:11
Duplicate of #593

**Closed by langovoi** 2018-11-26 19:11 UTC
