### ISSUE TITLE
Usage without babel?

### ISSUE THREAD

**Issue by ForsakenHarmony** [danger/danger-js#357] opened 2017-08-27 20:30 UTC
Currently it seem to be impossible to use danger without babel, which I find very confusing

**Comment by orta** [comment] 2017-08-27 20:52
Can you explain how you came to that conclusion? This has definitely been built with Babel and TypeScript as being optional in mind

**Comment by ForsakenHarmony** [comment] 2017-08-27 21:03
https://github.com/siddharthkp/bundlesize/pull/114#discussion_r135420266

**Comment by SaraVieira** [comment] 2017-08-29 08:52
@orta 

I keep getting `ReferenceError: regeneratorRuntime is not defined`, any idea what's up ?

Here is the build:
https://travis-ci.org/siddharthkp/bundlesize/builds/269493866?utm_source=github_status&utm_medium=notification
And the PR: https://github.com/siddharthkp/bundlesize/pull/118

Thanks :)

**Comment by orta** [comment] 2017-08-29 10:45
You're using alpha 1, that's been a lot of changes since then - so I'm not sure what's up. 

Does sound like babel is compiling your dangerfile and it's expecting the runtime regenerator to be available to danger

**Comment by SaraVieira** [comment] 2017-08-29 11:25
The problem is that if I use the version before it breaks because of babel 😞

**Comment by orta** [comment] 2017-08-29 12:11
The 2.x branches are classed as alphas because they're unstable, but a1 is being broken because of babel - I did make a release with some babel fixes last night based on your PRs, but it's hard to know if it fixed it as I got other babel issues when I tested it in production https://github.com/styled-components/styled-components/pull/1122

**Comment by SaraVieira** [comment] 2017-08-29 12:19
I'll install babel as a Dev dependecy then and wait for the 2.0 releases to be stable so I can take it out! 

Thanks!

**Comment by macklinu** [comment] 2017-08-30 14:34
I'm wondering if we should be publishing 2.0.0 alpha builds using an alpha or next [dist-tag](https://docs.npmjs.com/getting-started/using-tags). 

```
❯ npm view danger dist-tags
{ latest: '2.0.0-alpha.13' }
```

I think the alpha builds will be installed by default when running `npm install danger`, which could cause confusion for new adopters of danger. Lemme know if we want a separate issue for this, @orta.

[Another helpful article](http://jbavari.github.io/blog/2015/10/16/using-npm-tags/)

**Comment by orta** [comment] 2017-08-30 14:56
Ah - I'd say this is a bug with the dependency resolver in npm/yarn, as the rest of the dependency manager ecosystem doesn't resolve alphas like that - but its probably "feature not bug". 

I'll mark these as alphas

**Comment by orta** [comment] 2017-10-22 21:28
These release have been marked as alphas for the last few releases, so I'm going to close this

**Closed by orta** 2017-10-22 21:28 UTC
